name: Documentation
description: Report documentation errors or suggest improvements.
title: "[Docs]: "
labels:
  - documentation

body:
  - type: input
    id: document
    attributes:
      label: Document
      placeholder: CONTRIBUTING.md

  - type: textarea
    id: issue
    attributes:
      label: Problem
      description: What is incorrect or missing?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement